package com.plohoy.generator.model;

public enum EndPointType {
    CONTROLLER_END_POINT,
    CREATE_END_POINT,
    FIND_END_POINT,
    FIND_ALL_END_POINT,
    UPDATE_END_POINT,
    DELETE_SOFTLY_END_POINT,
    DELETE_HARDLY_END_POINT,
    RESTORE_END_POINT,
    SEARCH_END_POINT
}
