package com.plohoy.generator.model;

public enum EntryPointType {
    MAIN_ENTRY_POINT,
    CREATE_ENTRY_POINT,
    GET_ONE_ENTRY_POINT,
    FIND_ALL_ENTRY_POINT,
    UPDATE_ENTRY_POINT,
    DELETE_SOFTLY_ENTRY_POINT,
    DELETE_HARDLY_ENTRY_POINT,
    SEARCH_ENTRY_POINT
}
